name: Deploy to Aliyun Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to Aliyun Server
      run: |
        scp -r ./dist/* ${{ secrets.ALISERVER_USERNAME }}@${{ secrets.ALISERVER_HOST }}:~/hello


      env:
        NODE_ENV: production
