name: Deploy to Aliyun Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # - name: Set up Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: 14

    # - name: Install Dependencies
    #   run: npm install

    # - name: Build
    #   run: npm run build

    - name: Clear to Aliyun Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.ALISERVER_HOST }}
        username: ${{ secrets.ALISERVER_USERNAME }}
        password: ${{ secrets.ALISERVER_PASSWORD }}
        port: ${{ secrets.ALISERVER_PORT }}
        script: |
          rm -rf ~/hello/*
    - name: Deploy to Aliyun Server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.ALISERVER_HOST }}
        username: ${{ secrets.ALISERVER_USERNAME }}
        password: ${{ secrets.ALISERVER_PASSWORD }}
        port: ${{ secrets.ALISERVER_PORT }}
        source: public
        target: ~/hello
      
    env:
      NODE_ENV: production
